version: 0.0.1
config_file_name: config.yaml
# settings for path (changable)
input_dir: geo_input
# country_input_dir: test_country/
results_dir: results/

# settings for logging (default settings)
logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

node_file: four_nodes # four_nodes_comparison