version: 0.0.1
config_file_name: config.yaml
# settings for path (changable)
results_dir: results/
input_dir: geo_input
country_input_dir: EU_no_land_constraints_all/
output_folder: test/

# settings for logging (default settings)
logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"