name: snakemake-test
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10.8
  - pip
  - pypsa==0.22.1
  - atlite>=0.2.9
  - dask
  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - pre-commit
  - yaml
  - pytables
  - lxml
  - numpy
  - pandas==1.4.3
  - geopandas>=0.11.1
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - pyomo
  - matplotlib
  - proj
  - python-benedict
  # Keep in conda environment when calling ipython
  - ipython
  - ipykernel==6.21.3
  # GIS dependencies:
  - cartopy
  - descartes
  - rasterio
  - geopy
  - tqdm
  - pytz
  - ipykernel
  - fiona <= 1.18.20  # Till issue https://github.com/Toblerity/Fiona/issues/1085 is not solved
  - pip:
    - linopy==0.1.3
    - tabulate==0.8.10
    - vresutils>=0.3.1
    - tsam>=1.1.0
    - black
    - cdsapi
    - git+https://github.com/Tomkourou/snakemake.git